### ISSUE TITLE
uninitialized constant Plaid (NameError)

### ISSUE THREAD

**Issue by knubie** [plaid/plaid-ruby-legacy#4]
After switching our Gemfile in our rails app to use `plaid-legacy` instead of `plaid` 3.0.x we're now getting this error in `/config/initializers/plaid.rb`.

The only thing we've changed is the Gemfile(.lock). Is there a guide somewhere for moving from `plaid` to `plaid-legacy`?

**Comment by michaelckelly** [comment]
Thanks for the heads up @knubie -- apologies for not jumping on this issue sooner. Have you been able to resolve this issue? If not, we'll dig into this ASAP.

**Comment by be9** [comment]
@knubie Please try the following in your Gemfile:

```ruby
gem 'plaid-legacy', require: 'plaid'
```
